### ISSUE TITLE
How is it better than https://github.com/datopian/flexidate ?

### ISSUE THREAD

**Issue by KOLANICH** [pudo/prefixdate#1]

**Comment by pudo** [comment]
By the looks of it, two very different tools. Flexidate seems to deal with (or at least capture) a lot of the complexity of how humans describe time. Super versatile parser, but probably also some rate of false positives. This package really just does what it says on the tin and handles date prefixes (2000, 2002-05, 2005-08-01 etc.) and lets you reflect on how precise they are. It's not means to be a probabilistic parser. We may introduce a notion of "circa" in the future, since it comes up a lot. 

On a more technical level, `dateutil` is slow as hell. prefixdate does one regex (or, sometimes, one strpftime) to parse, so it works quite well on larger sets of data where guessing would be a bit more expensive.

**Comment by KOLANICH** [comment]
Thanks.
